[package]
name = "RustPractice"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "random_number"
path = "src/random_number.rs"
[dependencies]
rand = "0.8.5"